export Button from './button/button.js'
export Input from './input/input.js'
export StaticInput from './static-input/static-input.js'
export Avatar from './avatar/avatar'
export Link from './link/link'
